apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: koxakmrtv-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: koxakmrtv-go 
  name: koxakmrtv-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: koxakmrtv-go 
